### ISSUE TITLE
Support for ruby 1.9 and 2

### ISSUE THREAD

**Issue by mbusb** [ryanbooker/rubyscript2exe#2]
Is there any plan for supporting rubyscript2exe for latest version of ruby. Your gem is what exactly i am looking for. But unfortunatily it is not been updated years.

**Comment by ryanbooker** [comment]
Sorry for the delay. I don't really look at this anymore. I fixed it many moons ago for a specific project and haven't look at it since. If I get some time I may look at updating it. However, feel free to fork/fix if you like. I don't think there is an authoritative repo anymore (which was why I ended up fixing it myself all those years ago.)

**Comment by mbusb** [comment]
Thanks for the reply. Due to this issue i have already shifted my code base to python.
